packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.3.0
  eslint: ^9.35.0

catalogs:
  shared:
    better-auth: ^1.3.8
    consola: ^3.4.2
    zod: ^4.1.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - vue-demi
