/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.3_@babel+parser@7.28.4_axios@1.12.2_change-case@5.4.4_embla-carousel@8.6.0_1d833f0a86fff6336297b1aa71879900/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UContainer: typeof import('./../../node_modules/.pnpm/@nuxt+ui@3.3.3_@babel+parser@7.28.4_axios@1.12.2_change-case@5.4.4_embla-carousel@8.6.0_1d833f0a86fff6336297b1aa71879900/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  }
}
