import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import { notoSansSC, outfit } from "@/lib/fonts";
import Providers from "@/providers";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  params: Promise<object>;
  children: React.ReactNode;
}>;

export default async function RootLayout({ children }: Props) {
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      /**
       * @source https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
       */
      suppressHydrationWarning
    >
      <link
        href="https://fonts.gstatic.com&quot;"
        rel="preconnect"
      />

      <body className={`${outfit.variable} ${notoSansSC.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
