import type { Metadata } from "next";
import { Noto_Sans_SC, Outfit } from "next/font/google";
import { Providers } from "@/app/providers";

import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const notoSansSC = Noto_Sans_SC({
  variable: "--font-noto-sans-sc",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <link
        href="https://fonts.gstatic.com&quot;"
        rel="preconnect"
      />

      <body className={`${outfit.variable} ${notoSansSC.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
